# Classification de plantes

## Imports

### Library

In [1]:
# Imports de base
import os
import pandas as pd
import numpy as np

# Classification sans features
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression

# Mesures : accuracy , rappel, précision, f1 score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

# Skimage 
from skimage import io
from skimage import transform
from skimage.util import img_as_ubyte
from skimage.util import img_as_int

# MultiThreading
from joblib import Parallel, delayed

### Supprimer les warnings futurs

In [2]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

## Chargement des données

In [3]:
file = ".."+os.sep+"data"+os.sep+"raw_data"+ os.sep + "metadata.csv"
df = pd.read_csv(file,sep=",")
df.head()

observationid  mediaid  vote content  classid         family      genus  \
0          15010   100019   3.0  Flower     8527     Asteraceae   Achillea   
1          10732   100056   4.0  Flower     4516  Ranunculaceae    Ficaria   
2          24005   100087   4.0  Flower      588     Asteraceae  Centaurea   
3          19892   100182   4.0  Flower     9930    Orchidaceae  Epipactis   
4          36220    10019   4.0  Flower     6487    Orchidaceae     Ophrys   

                             species                 author       date  \
0            Achillea millefolium L.         mathieu menand  2009-4-24   
1                Ficaria verna Huds.                alain06   2014-9-7   
2                 Centaurea jacea L.         thierry pernot   1800-1-1   
3  Epipactis helleborine (L.) Crantz         thierry pernot   1800-1-1   
4               Ophrys apifera Huds.  jean-claude echardour  2010-6-26   

     location  latitude  longitude     yearinclef  observationid2014  \
0  Aucamville       NaN        NaN  PlantCLEF2014             4688.0   
1        Biot  43.62495    7.10440  PlantCLEF2015                NaN   
2         NaN       NaN        NaN  PlantCLEF2014             2559.0   
3         NaN       NaN        NaN  PlantCLEF2014            11733.0   
4      Saffré  47.49689   -1.59442  PlantCLEF2014            13210.0   

   imageid2014 learntag  
0      52287.0    Train  
1          NaN    Train  
2      32864.0    Train  
3      40782.0    Train  
4       8080.0    Train

### Combien de données (photos) on a pour chaque espèce

In [4]:
df.groupby('species')['mediaid'].count()

species
Achillea millefolium L.                                     62
Aconitum napellus L.                                        61
Anacamptis morio (L.) R.M.Bateman, Pridgeon & M.W.Chase     49
Anacamptis pyramidalis (L.) Rich.                           85
Anemone alpina L.                                           52
Anemone hepatica L.                                         52
Anemone nemorosa L.                                         55
Aquilegia vulgaris L.                                       75
Astrantia major L.                                          56
Bellis perennis L.                                          97
Centaurea aspera L.                                         65
Centaurea jacea L.                                          66
Chelidonium majus L.                                        60
Cichorium intybus L.                                       109
Cirsium vulgare (Savi) Ten.                                 58
Cistus albidus L.                              

### Nombre total de données

In [5]:
tailleTotale = df.mediaid.unique().size
print(tailleTotale)

3474


## Plan des étapes à faire
    Faire la somme cumulée des plantes : si y'a un gros pic => on a une espècee qui représente une grosse partie des données
    
    Est ce que les données sont bien balancées? 
    
    Métrique: comment comparer les différents modèles? 
    Si données pas trop balancées: accuracy pas trop mal pour mesurer!
    Moyenner par espèce: taux moyen pour chaque espèce
    Mesurer le taux d'erreur : données non balancées (issues de l'app plantNet: attiré plus vers certaines plantes plutot que d'autres) 
    stratifySplit (split, trainset split) 
    
    1) Prendre une baseline basique : 
        - Prendre un classifieur le plus naif possible et calculer son accuracy et on aura un accuracy de base 
        - permet de donner un sens aux chiffres 
        - Si moins bien que le truc très naif c'est qu'il y a un soucis
    2) Mettre les images en entrée et de regarder ce qui sort d'un classifier linéaire. 
        a) Redimensionner : vectoriser 
        b) Balancer au classifier: tableau 3D 
    3) https://scikit-image.org/docs/stable/auto_examples/features_detection/plot_hog.html#sphx-glr-auto-examples-features-detection-plot-hog-py
    Celui ci retire les couleurs: importants pour les fleurs
    Descripteur global sur image : si rotation alors problème , baisse de luminosité etc..
    
    Combiner les descripteurs : hog combiné à un descripteur de couleurs
    
    4) Bag-of-Visual-Words (BoVW) : Prend les descripteurs et en fait une représentation (marche plutot bien)
    
    5) Réseau neuronal : passer en entrée les images et lui va apprendre les features
    Pytorch: CNN (exemples tutos) 
    MLP (Multi Layer perceptron : bcp plus rapide que le convutionnel)
    Transfer learning : prendre un autre modele déja entrainé et le réutiliser : utile qd on a peu de données
    Meilleur pour réseau neuronnaux de partir d'un modèle pré-enrtainé

## Classification naïve: prédire toujours même classe (BaseLine)

C'est le classifieur le plus bas : si on a plu bas c'est qu'il y a un soucis qqs part.

Papaver rhoeas L.                                          119 (à prédire)

Calculer accuracy , f-measure, rappel

Accuracy = nbre d'éléments corrects / nombre total
Précision = nbre d'éléments corrects pour la classe / nbre prédit
Rappel = nbre d'éléments correctement attribués à la classe / nbre de documents appartenant à la classe i (ici 119) 

In [6]:
# Définition de la prédiction qui prédit toujours la même classe (avec la classe qui a le plus de photo)
def naivePredict(row):
    return 30269

In [7]:
# Application de la prédiction naïve sur toutes les lignes du dataframe
def predictionNaive(df):
    count = 0
    for index, row in df.iterrows():
        res = naivePredict(row)
        if (res == row["classid"]):
            count = count + 1
    #print("count : ", count)
    acc = count / tailleTotale
    prec = count / tailleTotale
    rappel = count / 119
    print("Accuracy : ", acc)
    print("Précision : ", prec)
    print("Rappel : ", rappel)
    

In [8]:
# Test prediction naive : 
predictionNaive(df)

Accuracy :  0.03425446171560161
Précision :  0.03425446171560161
Rappel :  1.0


## Classification sans features (SVM, LR)

Réduire la taille de l'image car taille d'image trop grande (ne rentrera pas en mémoire) => descripteur de taille + petite

### Load Train data without features

In [9]:
threads = 6
subset = 'train'

folder = ".."+ os.sep + "data" + os.sep
file =  subset + os.sep + subset + ".csv"

train_raw_df = pd.read_csv(folder + file,sep=",")
train_raw_df.head()

observationid  mediaid  vote content  classid       family           genus  \
0          12510     1648   4.0  Flower     4369  Primulaceae         Primula   
1          27147   111066   3.0  Flower    30162  Orchidaceae  Himantoglossum   
2          35639    17104   3.0  Flower     6538  Orchidaceae      Anacamptis   
3          18747    30734   3.0  Flower     6415  Orchidaceae          Orchis   
4          26828    71634   4.0  Flower     5148   Salicaceae           Salix   

                                             species            author  \
0                                   Primula veris L.  liliane roubaudi   
1               Himantoglossum hircinum (L.) Spreng.   julien barataud   
2  Anacamptis morio (L.) R.M.Bateman, Pridgeon & ...      marie portas   
3                     Orchis anthropophora (L.) All.        errol vela   
4                                    Salix caprea L.    inge wullweber   

        date                 location  latitude  longitude     yearinclef  \
0   2014-4-1  La Chapelle en Guinchay       NaN        NaN  PlantCLEF2015   
1  2006-6-14                 Plévenon       NaN        NaN  ImageCLEF2013   
2  2012-3-19                   Hyères       NaN        NaN  ImageCLEF2013   
3  2014-4-11       Sidi Aich, ALGERIE   36.6026    4.69448  PlantCLEF2015   
4  2009-3-11                      NaN       NaN        NaN  PlantCLEF2014   

   observationid2014  imageid2014 learntag  
0                NaN          NaN    Train  
1            14913.0      48553.0    Train  
2             6637.0      33907.0    Train  
3                NaN          NaN    Train  
4             2982.0      58691.0    Train

In [10]:
loadpath = folder + 'resized' + os.sep + subset + os.sep

### Classifieurs

In [11]:
models_classifiers = []
models_classifiers.append(('LinearSVC', LinearSVC(random_state=0, tol=1e-5)))
models_classifiers.append(('SGDClassifier', SGDClassifier(loss="hinge", penalty="l2", max_iter=5)))
models_classifiers.append(('LR', LogisticRegression()))

### Train Classifiers

In [12]:
def imgToVector(fname):
    image = io.imread(loadpath + fname)
    image = img_as_ubyte(image)
    vector = image.reshape(300*300*3)
    #vector = vector.flatten()
    return vector

In [13]:
liste_image = Parallel(n_jobs=threads)(delayed(imgToVector)(str(i) + '.jpg') for i in train_raw_df['mediaid']);

In [14]:
#Regarde comment c'est magique la liste d'images tout d'un coup et parallelise en plus  ! ;)
liste_image

[array([14, 13, 18, ...,  6,  6,  8], dtype=uint8),
 array([153, 152,  98, ...,  63,  73,  23], dtype=uint8),
 array([ 98,  41,  96, ..., 144, 152,  93], dtype=uint8),
 array([167, 146,  53, ...,  39,  45,   9], dtype=uint8),
 array([ 64,  92, 132, ...,  57,  56,  38], dtype=uint8),
 array([ 68,  87,  41, ..., 196, 207, 209], dtype=uint8),
 array([  1,   3,   0, ..., 170, 160,  98], dtype=uint8),
 array([ 77, 130,  12, ...,  38,  85,  17], dtype=uint8),
 array([ 52,  84, 105, ...,  59,  90, 108], dtype=uint8),
 array([110,  94,  69, ...,  67,  54,  37], dtype=uint8),
 array([ 76, 130,  34, ...,  80,  86,  82], dtype=uint8),
 array([120, 124, 109, ...,  51,  51,  61], dtype=uint8),
 array([46, 48, 45, ..., 15, 27, 17], dtype=uint8),
 array([15, 28,  2, ..., 99, 78, 49], dtype=uint8),
 array([ 84,  77,  58, ..., 113,  92,  75], dtype=uint8),
 array([195, 194, 212, ..., 150, 135, 106], dtype=uint8),
 array([ 43,  74,  58, ..., 136, 120, 149], dtype=uint8),
 array([18, 20,  6, ..., 22, 40,

In [ ]:
y_train = train_raw_df['classid']

X_train = liste_image
for name, clf in models_classifiers:
   clf.fit(X_train, y_train)

# liste_image = []

# for image in vect:
#     vector = image.reshape(-1, 300*300*3)
#     vector = vector.flatten()
#     liste_image.append(vector)


# df_train = pd.DataFrame(liste_image)
# df_train.head()

## Classification basique avec features (SVM, LR)

### Load data with features to train

In [7]:
#Load Train Data
subset = 'train'

folder = ".."+os.sep+"data"+os.sep
file =  subset + os.sep + subset + ".csv"

train_raw_df = pd.read_csv(folder + file,sep=",")
train_raw_df.head()

hogpath = folder + 'resized' +os.sep+ subset + os.sep + subset + "_hog.csv"
train_hog_df = pd.read_csv(hogpath,sep=",")
train_hog_df.head()

0         1         2         3         4         5         6  \
0  0.485814  0.485814  0.219438  0.159252  0.485814  0.000000  0.289532   
1  0.353553  0.353553  0.353553  0.353553  0.353553  0.353553  0.353553   
2  0.397287  0.085241  0.086637  0.062499  0.453730  0.453730  0.453730   
3  0.392025  0.392025  0.254712  0.114115  0.392025  0.392025  0.392025   
4  0.545601  0.545601  0.465610  0.097398  0.287365  0.042790  0.303704   

          7         8         9  ...      7190      7191      7192      7193  \
0  0.366892  0.548796  0.229304  ...  0.560253  0.000000  0.544908  0.265194   
1  0.353553  0.436803  0.436803  ...  0.377178  0.377178  0.380913  0.380913   
2  0.453730  0.394855  0.023979  ...  0.518920  0.075144  0.123989  0.000000   
3  0.392025  0.512384  0.512384  ...  0.554194  0.000000  0.336845  0.251069   
4  0.041401  0.678511  0.171469  ...  0.322494  0.108256  0.439907  0.439907   

       7194      7195      7196      7197      7198      7199  
0  0.192605  0.000000  0.544908  0.203023  0.486721  0.143559  
1  0.226869  0.380913  0.380913  0.279218  0.380913  0.380913  
2  0.245486  0.000000  0.655185  0.588457  0.385764  0.000000  
3  0.452526  0.000000  0.731430  0.218635  0.189550  0.000000  
4  0.439907  0.321641  0.439907  0.091582  0.069689  0.330503  

[5 rows x 7200 columns]

### Classifieurs

In [10]:
models_classifiers = []
models_classifiers.append(('LinearSVC', LinearSVC(random_state=0, tol=1e-5)))
models_classifiers.append(('SGDClassifier', SGDClassifier(loss="hinge", penalty="l2", max_iter=5)))
models_classifiers.append(('LR', LogisticRegression()))

### Train classifiers

In [11]:
X_train = train_hog_df
y_train = train_raw_df['classid']

In [12]:
for name,clf in models_classifiers:
    clf.fit(X_train, y_train)

/home/camille/M2/HMIN339M - Méthodes avancées de la science de données/ClassificationPlantes/env/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/camille/M2/HMIN339M - Méthodes avancées de la science de données/ClassificationPlantes/env/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/home/camille/M2/HMIN339M - Méthodes avancées de la science de données/ClassificationPlantes/env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/camille/M2/HMIN339M - Méthodes avancées de la science de données/ClassificationPlantes/env/lib/pyth

### Load Test data

In [13]:
#Load Test Data
subset = 'test'
file =  subset + os.sep + subset + ".csv"

test_raw_df = pd.read_csv(folder + file,sep=",")
test_raw_df.head()

hogpath = folder + 'resized' +os.sep + subset + os.sep + subset + "_hog.csv"
test_hog_df = pd.read_csv(hogpath,sep=",")
test_hog_df.head()

0         1         2         3         4         5         6  \
0  0.204076  0.000000  0.382911  0.615967  0.615967  0.225245  0.046550   
1  0.415877  0.092098  0.111781  0.338016  0.415877  0.415877  0.415877   
2  0.241196  0.108855  0.098362  0.206433  0.537167  0.537167  0.537167   
3  0.365089  0.312301  0.365089  0.365089  0.365089  0.365089  0.365089   
4  0.521317  0.521317  0.508100  0.138390  0.357581  0.000000  0.220705   

          7         8         9  ...      7190      7191      7192      7193  \
0  0.000000  0.479311  0.000000  ...  0.361670  0.361670  0.399978  0.130546   
1  0.415877  0.325248  0.022220  ...  0.264512  0.054895  0.419615  0.419615   
2  0.109723  0.398204  0.155901  ...  0.116798  0.016864  0.468831  0.234810   
3  0.320509  0.374733  0.374733  ...  0.536307  0.000000  0.458736  0.401347   
4  0.050648  0.381562  0.381562  ...  0.393497  0.207274  0.486437  0.486437   

       7194      7195      7196      7197      7198      7199  
0  0.399978  0.399978  0.399978  0.399978  0.399978  0.151862  
1  0.244430  0.153779  0.419615  0.419615  0.419615  0.190322  
2  0.206926  0.468831  0.468831  0.000000  0.151114  0.468831  
3  0.124761  0.300086  0.458736  0.189660  0.458736  0.256940  
4  0.479151  0.110677  0.472375  0.023688  0.059926  0.240071  

[5 rows x 7200 columns]

### Test Classifiers

In [14]:
X_test = test_hog_df
y_true = test_raw_df['classid']

y_predicts = []
for name,clf in models_classifiers:
    y_predicts.append(clf.predict(X_test))

In [15]:
for y_predict in y_predicts:
    print("Accuracy: " + str(accuracy_score(y_true, y_predict)))
    print("Rappel: " + str(recall_score(y_true, y_predict,average='micro')))
    print("Precision: " + str(precision_score(y_true, y_predict,average='micro')))
    print("F-Measure: " + str(precision_score(y_true, y_predict,average='micro')))

Accuracy: 0.13525179856115108
Rappel: 0.13525179856115108
Precision: 0.13525179856115108
F-Measure: 0.13525179856115108
Accuracy: 0.09928057553956834
Rappel: 0.09928057553956834
Precision: 0.09928057553956834
F-Measure: 0.09928057553956834
Accuracy: 0.14964028776978416
Rappel: 0.14964028776978416
Precision: 0.14964028776978416
F-Measure: 0.14964028776978416
